[variables]
    NIXPACKS_METADATA = 'node'

[phases.setup]
    nixPkgs = ['nodePackages.npm', 'playwright-driver']

[phases.build]
    cmds = ['npm install', 'npx playwright install chromium --with-deps']
